name: Babel Auto-updater
on:
  schedule:
    - cron: 10 11 * * *

jobs:
  babel-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Update to latest version
        id: update
        run: ./update_babel.sh
      - name: Verify
        if: env.UPDATE == env.LATEST_VERSION
        run: go test ./...
      - name: Commit
        if: env.UPDATE == env.LATEST_VERSION
        run: |
          git config --global user.name 'Babel Auto-updater action'
          git config --global user.email 'jvatic@users.noreply.github.com'
          BABEL_VERSION=$(cat babel_version.txt)
          git commit -am "Bump babel version to $BABEL_VERSION"
          git push
          git tag babel-$BABEL_VERSION
          git push --tags
